### ISSUE TITLE
Is the MRI dataset T1 or T2 weighted

### ISSUE THREAD

**Issue by zheangh** [CSCYQJ/MICCAI23-ProtoContra-SFDA#16]
Hello! Thank you for sharing the wonderful work.
In your paper, you mention that the MRI volumes are from the 2019 CHAOS Challenge. The MRI in CHAOS has T1DUAL and T2SPIR, and T1DUAL has InPhase and OutPhase. Which one is used in the paper? It seems there are no issues asking this but I am confused about it. Thanks!

**Comment by derekshiii** [comment]
in the code of the preprocess.ipynb, the author use T2SPIR to conduct this experiment

**Comment by zheangh** [comment]
@derekshiii Thanks!
