### ISSUE TITLE
Train.py

### ISSUE THREAD

**Issue by Huster-Hq** [CSCYQJ/MICCAI23-ProtoContra-SFDA#3]
Thank you for your excellent work！

After reading your **main_trainer_source.py**, I have some questions:
1. File default seems to be using the pseudo_label_trainer, which not includes your proposed PFA and CL.
2. I only see PFA_trainer and CL_trainer individually, I don't see the combination of them, i.e., SFDA.

I'm sorry if I made a mistake. Looking forward to your reply!

**Comment by CSCYQJ** [comment]
Thanks for your questions!

- Q1. The pseudo-label trainer is not directly-related to the paper, and I just add it to verify some SSL pseudo-label based methods for the SFDA problem. 
- Q2. As described in our paper, the CL stage is the consequent stage of PFA stage. (i.e. First PFA then CL)

**Comment by Huster-Hq** [comment]
Thanks for your reply!
