### ISSUE TITLE
Some questions about preprocessing

### ISSUE THREAD

**Issue by fly-beep** [CSCYQJ/MICCAI23-ProtoContra-SFDA#4]
I would like to ask, when I reproduce it, do I need to preprocess the downloaded data set?

**Comment by CSCYQJ** [comment]
Yes, you are supposed to prepocess the rawdata as described in the Sec 3.1. For more details, you can read the following paper which have a similar prepocessing with us:
[https://www.sciencedirect.com/science/article/abs/pii/S0950705122005743](url)

**Comment by fly-beep** [comment]
Thank you！
