### ISSUE TITLE
工程中各个package有import报错

### ISSUE THREAD

**Issue by derekshiii** [CSCYQJ/MICCAI23-ProtoContra-SFDA#8]
工程无论在colab还是在pycharm打开，在每个包的ini.py中，会有关于import的报错

![屏幕截图 2023-11-08 215004](https://github.com/CSCYQJ/MICCAI23-ProtoContra-SFDA/assets/102472253/f3320602-4ea5-460b-8436-d8d88b5d6d69)

**Comment by derekshiii** [comment]
已经解决了，是有surface-distance tensorboardX两个库没有安装。图片中的问题是导入的路径有问题。
还有一个小问题，就是utils下并没有distribution_estimation这个文件，
所以utils/_ini_.py中lin5：from .distribution_estimation import kmeans, pairwise_cosine，应该是有问题的

**Comment by ghost** [comment]
请问没有distribution_estimation.的问题您是怎么解决的？
